[[redirects]]
  from = "http://heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "http://www.heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "https://heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "https://www.heyreeves.com/*"
  to = "https://reeves.studio"
  force = true
