[[redirects]]
  from = "/js/data.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

[[redirects]]
  from = "http://heyreeves.com/calendar"
  to = "https://savvycal.com/heymarkreeves/meet"
  force = true

[[redirects]]
  from = "http://www.heyreeves.com/calendar"
  to = "https://savvycal.com/heymarkreeves/meet"
  force = true

[[redirects]]
  from = "https://heyreeves.com/calendar"
  to = "https://savvycal.com/heymarkreeves/meet"
  force = true

[[redirects]]
  from = "https://www.heyreeves.com/calendar"
  to = "https://savvycal.com/heymarkreeves/meet"
  force = true

[[redirects]]
  from = "http://reeves.studio/basecamp"
  to = "https://3.basecamp.com/5243460"
  force = true

[[redirects]]
  from = "https://reeves.studio/basecamp"
  to = "https://3.basecamp.com/5243460"
  force = true

[[redirects]]
  from = "http://heyreeves.com/basecamp"
  to = "https://3.basecamp.com/5243460"
  force = true

[[redirects]]
  from = "https://heyreeves.com/basecamp"
  to = "https://3.basecamp.com/5243460"
  force = true

[[redirects]]
  from = "http://heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "http://www.heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "https://heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "https://www.heyreeves.com/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "http://frosty-bohr-7890eb.netlify.app/*"
  to = "https://reeves.studio"
  force = true

[[redirects]]
  from = "https://frosty-bohr-7890eb.netlify.app/*"
  to = "https://reeves.studio"
  force = true
